/*
 * dig_inouts.h
 */

#ifndef INOUTS_H_
#define INOUTS_H_
#include <stm32f4xx.h>

//INPUTS

#define PING_RCC RCC_AHB1Periph_GPIOE

#define PINGBUT_pin GPIO_Pin_5
#define PINGBUT_GPIO GPIOE
#define PINGBUT (!(PINGBUT_GPIO->IDR & PINGBUT_pin))

// Infinite Repeat Button and Jack
#define INF_RCC RCC_AHB1Periph_GPIOA | RCC_AHB1Periph_GPIOC

//In p3 it's D5
#define INF1BUT_pin GPIO_Pin_13
#define INF1BUT_GPIO GPIOC
#define INF1BUT (!(INF1BUT_GPIO->IDR & INF1BUT_pin))

#define INF2BUT_pin GPIO_Pin_9
#define INF2BUT_GPIO GPIOA
#define INF2BUT (!(INF2BUT_GPIO->IDR & INF2BUT_pin))

#define REVBUT_RCC RCC_AHB1Periph_GPIOA | RCC_AHB1Periph_GPIOG

#define REV1BUT_pin GPIO_Pin_10
#define REV1BUT_GPIO GPIOG
#define REV1BUT (!(REV1BUT_GPIO->IDR & REV1BUT_pin))

#define REV2BUT_pin GPIO_Pin_1
#define REV2BUT_GPIO GPIOA
#define REV2BUT (!(REV2BUT_GPIO->IDR & REV2BUT_pin))

//OUTPUTS

//CLK OUT
#define CLKOUT_RCC RCC_AHB1Periph_GPIOE

#define CLKOUT_pin GPIO_Pin_3
#define CLKOUT_GPIO GPIOE
#define CLKOUT_ON CLKOUT_GPIO->BSRRL = CLKOUT_pin
#define CLKOUT_OFF CLKOUT_GPIO->BSRRH = CLKOUT_pin
#define CLKOUT_TRIG_TIME 960 /*20ms*/

//PING Button LED
#define PINGBUTLED_RCC RCC_AHB1Periph_GPIOE

#define LED_PINGBUT_pin GPIO_Pin_4
#define LED_PINGBUT_GPIO GPIOE
#define LED_PINGBUT_ON LED_PINGBUT_GPIO->BSRRL = LED_PINGBUT_pin
#define LED_PINGBUT_OFF LED_PINGBUT_GPIO->BSRRH = LED_PINGBUT_pin

//INF REPEAT Button LED
#define INF1_BUTLED_RCC RCC_AHB1Periph_GPIOD
#define LED_INF1_pin GPIO_Pin_4
#define LED_INF1_GPIO GPIOD
#define LED_INF1_ON LED_INF1_GPIO->BSRRL = LED_INF1_pin
#define LED_INF1_OFF LED_INF1_GPIO->BSRRH = LED_INF1_pin

#define INF2_BUTLED_RCC RCC_AHB1Periph_GPIOA
#define LED_INF2_pin GPIO_Pin_10
#define LED_INF2_GPIO GPIOA
#define LED_INF2_ON LED_INF2_GPIO->BSRRL = LED_INF2_pin
#define LED_INF2_OFF LED_INF2_GPIO->BSRRH = LED_INF2_pin

//REV Button LED
#define REV1_BUTLED_RCC RCC_AHB1Periph_GPIOA
#define LED_REV1_pin GPIO_Pin_15
#define LED_REV1_GPIO GPIOA
#define LED_REV1_ON LED_REV1_GPIO->BSRRL = LED_REV1_pin
#define LED_REV1_OFF LED_REV1_GPIO->BSRRH = LED_REV1_pin

#define REV2_BUTLED_RCC RCC_AHB1Periph_GPIOD
#define LED_REV2_pin GPIO_Pin_2
#define LED_REV2_GPIO GPIOD
#define LED_REV2_ON LED_REV2_GPIO->BSRRL = LED_REV2_pin
#define LED_REV2_OFF LED_REV2_GPIO->BSRRH = LED_REV2_pin

//LOOP LEDs
#define LED_RCC RCC_AHB1Periph_GPIOA

#define LED_LOOP1 GPIO_Pin_11
#define LED_LOOP2 GPIO_Pin_12
#define LED_GPIO GPIOA
#define LED_LOOP1_ON LED_GPIO->BSRRL = LED_LOOP1
#define LED_LOOP1_OFF LED_GPIO->BSRRH = LED_LOOP1
#define LED_LOOP2_ON LED_GPIO->BSRRL = LED_LOOP2
#define LED_LOOP2_OFF LED_GPIO->BSRRH = LED_LOOP2

//DEBUG pins
/*
#define DEBUG_RCC RCC_AHB1Periph_GPIOD | RCC_AHB1Periph_GPIOC

#define DEBUG0 GPIO_Pin_3
#define DEBUG0_GPIO GPIOD
#define DEBUG0_ON DEBUG0_GPIO->BSRRL = DEBUG0
#define DEBUG0_OFF DEBUG0_GPIO->BSRRH = DEBUG0

#define DEBUG1 GPIO_Pin_3
#define DEBUG1_GPIO GPIOD
#define DEBUG1_ON DEBUG1_GPIO->BSRRL = DEBUG1
#define DEBUG1_OFF DEBUG1_GPIO->BSRRH = DEBUG1

#define DEBUG2 GPIO_Pin_13
#define DEBUG2_GPIO GPIOC
#define DEBUG2_ON DEBUG2_GPIO->BSRRL = DEBUG2
#define DEBUG2_OFF DEBUG2_GPIO->BSRRH = DEBUG2

#define DEBUG3 GPIO_Pin_14
#define DEBUG3_GPIO GPIOC
#define DEBUG3_ON DEBUG3_GPIO->BSRRL = DEBUG3
#define DEBUG3_OFF DEBUG3_GPIO->BSRRH = DEBUG3

#define DEBUG4 GPIO_Pin_15
#define DEBUG4_GPIO GPIOC
#define DEBUG4_ON DEBUG4_GPIO->BSRRL = DEBUG4
#define DEBUG4_OFF DEBUG4_GPIO->BSRRH = DEBUG4
*/
#ifdef __cplusplus
extern "C" {
#endif

void init_dig_inouts(void);

#ifdef __cplusplus
}
#endif

#endif /* INOUTS_H_ */
